env:
  node: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  no-console: off
  semi: 1
  quotes: ['error', 'single']
  no-trailing-spaces: [2, { 'skipBlankLines': true }]
  prettier/prettier: error
  no-unused-vars: error
  no-use-before-define: [ 'error', { functions: false, variables: true } ]
  prefer-destructuring: ['error', { object: true, array: false}]
  import/extensions:
    - error
    - always
    - ignorePackages: true
  jest/no-disabled-tests: warn
  jest/no-focused-tests: error
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  jest/valid-expect: error
  "@typescript-eslint/ban-ts-comment":
    - error
    - ts-ignore: allow-with-description
